// One-time backfill: retroactively create the payment-free skip months that
// SHOULD have been auto-generated by past Double Chiti recordings, but weren't
// (because the auto-skip feature did not exist when those winners were recorded).
//
// For each group it computes:
//   extraWinners            = cycle_winners rows with winner_number >= 2  (one per Double Chiti)
//   existingPaymentFreeSkip = skip cycles that have NO winner  (already-created payment-free skips)
//   needed                  = extraWinners - existingPaymentFreeSkip
// and marks the `needed` highest-numbered Open, non-skip, winnerless cycles as
// payment-free skip months (is_skip_month = true, all non-Paid payments Waived ₹0).
// This mirrors exactly what cycles.service.ts:recordWinner now does going forward.
//
// SAFETY:
//   - Dry-run by default. Pass --apply to write.
//   - Idempotent: re-running counts already-created payment-free skips, so it
//     won't create duplicates.
//   - Manual skip-months (declareSkipMonth) HAVE a winner, so they are never
//     counted or touched here.
//   - Optionally scope to one group with --group <group_id>.
//
// Usage:
//   npx tsx src/scripts/backfill-double-chiti-skips.ts                 # dry-run, all open groups
//   npx tsx src/scripts/backfill-double-chiti-skips.ts --group <id>    # dry-run, one group
//   npx tsx src/scripts/backfill-double-chiti-skips.ts --apply         # apply to all open groups
//
// IMPORTANT: deploy the new backend code (cycles.service.ts) BEFORE running with
// --apply, so that when these skip cycles are seeded later, closeCycle waives them.

import '../config/env';
import { db } from '../config/db';
import { chit_groups, monthly_cycles, cycle_winners, payments } from '../db/schema';
import { and, eq, ne, sql, desc, count } from 'drizzle-orm';

const APPLY    = process.argv.includes('--apply');
const groupArg = process.argv.indexOf('--group');
const ONLY_GROUP = groupArg !== -1 ? process.argv[groupArg + 1] : null;

async function backfillGroup(group_id: string, group_name: string) {
  // Number of Double Chiti payouts = winner slots beyond the first.
  const [extra] = await db
    .select({ n: count() })
    .from(cycle_winners)
    .where(and(eq(cycle_winners.group_id, group_id), sql`${cycle_winners.winner_number} >= 2`));
  const extraWinners = Number(extra?.n ?? 0);

  if (extraWinners === 0) return; // no Double Chiti in this group

  // Already-created payment-free skips = skip cycles with no winner recorded.
  const [doneRow] = await db
    .select({ n: count() })
    .from(monthly_cycles)
    .where(and(
      eq(monthly_cycles.group_id, group_id),
      eq(monthly_cycles.is_skip_month, true),
      sql`NOT EXISTS (SELECT 1 FROM ${cycle_winners} cw WHERE cw.cycle_id = ${monthly_cycles.id})`,
    ));
  const alreadyDone = Number(doneRow?.n ?? 0);

  const needed = extraWinners - alreadyDone;

  console.log(`\nGroup "${group_name}" (${group_id})`);
  console.log(`  Double Chiti payouts: ${extraWinners} | payment-free skips already present: ${alreadyDone} | to create: ${Math.max(0, needed)}`);

  if (needed <= 0) {
    console.log('  ✓ Already consistent — nothing to do.');
    return;
  }

  // Candidate cycles to convert: Open, not already skip, no winner, highest month_number first.
  const candidates = await db
    .select({ id: monthly_cycles.id, month_number: monthly_cycles.month_number, month_label: monthly_cycles.month_label })
    .from(monthly_cycles)
    .where(and(
      eq(monthly_cycles.group_id, group_id),
      eq(monthly_cycles.status, 'Open'),
      eq(monthly_cycles.is_skip_month, false),
      sql`NOT EXISTS (SELECT 1 FROM ${cycle_winners} cw WHERE cw.cycle_id = ${monthly_cycles.id})`,
    ))
    .orderBy(desc(monthly_cycles.month_number))
    .limit(needed);

  if (candidates.length < needed) {
    console.log(`  ⚠ Only ${candidates.length} eligible cycle(s) available for ${needed} needed skip(s). Will convert what is available.`);
  }

  for (const c of candidates) {
    console.log(`  → ${c.month_label} (month ${c.month_number}) → payment-free skip`);
  }

  if (!APPLY) {
    console.log('  (dry-run — no changes written; pass --apply to commit)');
    return;
  }

  await db.transaction(async (tx) => {
    for (const c of candidates) {
      await tx.update(monthly_cycles)
        .set({ is_skip_month: true, notes: 'Payment-free month — saved by Double Chiti (backfill)' })
        .where(eq(monthly_cycles.id, c.id));

      await tx.update(payments)
        .set({ expected_amount: 0, paid_amount: 0, status: 'Waived', updated_at: new Date() })
        .where(and(eq(payments.cycle_id, c.id), ne(payments.status, 'Paid')));
    }
  });
  console.log(`  ✓ Applied ${candidates.length} skip(s).`);
}

async function main() {
  const groups = ONLY_GROUP
    ? await db.select({ id: chit_groups.id, name: chit_groups.name }).from(chit_groups).where(eq(chit_groups.id, ONLY_GROUP))
    : await db.select({ id: chit_groups.id, name: chit_groups.name }).from(chit_groups).where(ne(chit_groups.status, 'Closed'));

  if (groups.length === 0) {
    console.log('No matching groups found.');
    process.exit(0);
  }

  console.log(`Mode: ${APPLY ? 'APPLY (writing changes)' : 'DRY-RUN (no changes)'} | groups to scan: ${groups.length}`);
  for (const g of groups) {
    await backfillGroup(g.id, g.name);
  }

  console.log(`\nDone.${APPLY ? '' : ' Re-run with --apply to write changes.'}`);
  process.exit(0);
}

main().catch((err) => {
  console.error('Backfill failed:', err);
  process.exit(1);
});
